# 이 파일에는 실제 비밀키와 클라이언트 정보를 포함하는 application-secret.yml 문서의 샘플 파일입니다
# 반드시 .gitignore에 추가하여 git에 커밋하지 마세요
# 로컬에서는 직접 값을 넣거나, 환경변수를 통해 주입하세요

jwt:
  secret: your_real_jwt_secret_key_here


spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: your_kakao_client_id
            client-secret: your_kakao_client_secret
          naver:
            client-id: your_naver_client_id
            client-secret: your_naver_client_secret