spring:
  config:
    import: optional:application-secret.yml

server:
  port: 8080

jwt:
#  secret: ${JWT_SECRET} # secret: your_jwt_secret_key_here
  access-exp-minutes: 60
  cookie-name: access_token
  cookie-domain: localhost

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.security.oauth2.client: DEBUG

---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            provider: kakao
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: [profile_nickname, profile_image, account_email]
          naver:
            provider: naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: [name, email]

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri:          https://kauth.kakao.com/oauth/token
            user-info-uri:      https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri:  https://nid.naver.com/oauth2.0/authorize
            token-uri:          https://nid.naver.com/oauth2.0/token
            user-info-uri:      https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
